import requests
import json
import os
import time
import urllib.parse # NEW IMPORT for URL encoding

# --- Configuration ---
# NOTE: The server is running on port 8083 locally.
UPLOAD_URL = "http://127.0.0.1:8083/upload"
DOWNLOAD_URL_BASE = "http://127.0.0.1:8083/download"

# ⚠️ ACTION REQUIRED: REPLACE WITH A REAL, VALID JWT
# This token MUST be the one generated by your Auth Service. 
DUMMY_JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjE5MTk1OTUsImlhdCI6MTc2MTgzMzE5NSwidXNlcl9pZCI6IjFkZTJhMGIwLTBmN2ItNGE0MC1hMTJiLTk0YWQ3NTZjZTdlOCIsInRlYW1faWQiOiJ0ZWFtLWFscGhhLTEyMyJ9.U0IURVQ9CpK4TfcRDrzdlXpYagYGwgRuIUbUPkK6UeQ"

# --- Setup Test File ---
TEST_FILENAME = "test_document.txt"
# Create a unique file content to verify the upload
TEST_CONTENT = f"This is a test file for the file_handler_service. Timestamp: {time.time()}"

# --- Helper Functions ---
def create_dummy_file():
    """Creates a temporary local file for upload testing."""
    with open(TEST_FILENAME, "w") as f:
        f.write(TEST_CONTENT)
    print(f"Created dummy file: {TEST_FILENAME}")

def cleanup_file():
    """Removes the temporary local file."""
    if os.path.exists(TEST_FILENAME):
        os.remove(TEST_FILENAME)
        print(f"\nCleaned up dummy file: {TEST_FILENAME}")

def test_upload(token: str, filename: str):
    """Executes the file upload and reports the status."""
    create_dummy_file()
    
    headers = {
        "Authorization": f"Bearer {token}" 
    }
    
    # The key 'file' must match the FastAPI parameter name in the service
    files = {
        'file': (filename, open(filename, 'rb'), 'text/plain')
    }
    
    print(f"\n--- Starting Upload Test for {filename} ---")
    print(f"Attempting to upload to {UPLOAD_URL}...")

    try:
        response = requests.post(UPLOAD_URL, headers=headers, files=files)
        
        # Ensure the file handle is closed immediately after the request
        files['file'][1].close() 
        
        if response.status_code == 200:
            print(f"\n✅ UPLOAD SUCCESSFUL (HTTP 200) for {filename}")
            response_data = response.json()
            print("Response Body:")
            print(json.dumps(response_data, indent=2))
            return response_data.get('filename') # Return the unique S3 key/filename
        else:
            print(f"\n❌ UPLOAD FAILED (HTTP {response.status_code})")
            
            # Detailed Error Handling
            if response.status_code == 401:
                print("       -> Reason: 401 Unauthorized. Check if your DUMMY_JWT_TOKEN is valid and has not expired.")
            elif response.status_code == 422:
                print("       -> Reason: 422 Unprocessable Content. The server didn't find the expected 'file' field in the form data.")
            
            try:
                error_details = response.json()
                print("Error Details:")
                print(json.dumps(error_details, indent=2))
            except json.JSONDecodeError:
                print("Server returned non-JSON error response:")
                print(response.text)
            return None

    except requests.exceptions.RequestException as e:
        print(f"\n❌ REQUEST EXCEPTION: An error occurred connecting to the server: {e}")
        return None
    finally:
        cleanup_file()

def test_download(token: str, unique_filename: str):
    """Executes a file download test."""
    print(f"\n--- Starting Download Test for {unique_filename} ---")
    
    # FIX: Use urllib.parse.quote to ensure slashes ('/') are encoded as '%2F' 
    # This is the correct behavior for the client.
    encoded_filename = urllib.parse.quote(unique_filename, safe='')
    download_url = f"{DOWNLOAD_URL_BASE}/{encoded_filename}"
    
    print(f"Encoded URL used for download: {download_url}")
    
    headers = {"Authorization": f"Bearer {token}"}
    
    try:
        response = requests.get(download_url, headers=headers)
        
        if response.status_code == 200:
            downloaded_content = response.text
            print("✅ DOWNLOAD SUCCESSFUL (HTTP 200)")
            if downloaded_content.strip() == TEST_CONTENT.strip():
                print("       -> Content Verified: Downloaded content matches uploaded content!")
            else:
                print("       -> Content Mismatch: Downloaded content is different.")
        else:
            print(f"\n❌ DOWNLOAD FAILED (HTTP {response.status_code})")
            if response.status_code == 401:
                print("       -> Reason: 401 Unauthorized. Token issue.")
            elif response.status_code == 404:
                print("       -> Reason: 404 Not Found. File key was likely lost/misinterpreted during routing.")
            else:
                print(response.text)

    except requests.exceptions.RequestException as e:
        print(f"\n❌ DOWNLOAD REQUEST EXCEPTION: {e}")

# --- Main Execution ---
if __name__ == "__main__":
    
    # 1. Test Upload
    uploaded_file_id = test_upload(DUMMY_JWT_TOKEN, TEST_FILENAME)
    
    # 2. Test Download (Only if upload was successful)
    if uploaded_file_id:
        test_download(DUMMY_JWT_TOKEN, uploaded_file_id)
    
    print("\n--- Test sequence complete. ---")
